kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nrocinu
  namespace: nrocinu
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
