kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nrocinu
  namespace: nrocinu
subjects:
- kind: User
  name: nrocinu
  apiGroup: ""
roleRef:
  kind: Role
  name: nrocinu
  apiGroup: ""
