apiVersion: v1
kind: Service
metadata:
    name: models
    namespace: nrocinu
spec:
    selector:
        app: models
    ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: http
