apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: postgres
    name: postgres
    namespace: nrocinu
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "9187"
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:14
                  imagePullPolicy: Always
                  envFrom:
                      - secretRef:
                            name: postgres
                  ports:
                      - name: postgres
                        containerPort: 5432
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
                - name: exporter
                  image: bitnami/postgres-exporter:0
                  imagePullPolicy: Always
                  env:
                      - name: DATA_SOURCE_URI
                        value: localhost?sslmode=disable
                      - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
                        value: "true"
            volumes:
                - name: postgres-storage
                  hostPath:
                    path: /opt/nrocinu/postgres
