apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: nrocinu
type: Opaque
data:
    POSTGRES_DB: cG9zdGdyZXM=
    POSTGRES_USER: cG9zdGdyZXM=
    POSTGRES_PASSWORD: cG9zdGdyZXM=
    DATA_SOURCE_USER: cG9zdGdyZXM=
    DATA_SOURCE_PASS: cG9zdGdyZXM=
