apiVersion: v1
kind: Service
metadata:
    name: postgres
    namespace: nrocinu
spec:
    selector:
        app: postgres
    ports:
        - name: postgres
          protocol: TCP
          port: 5432
          targetPort: postgres
