name: warmbet

on:
  push:
    paths:
      - "warmbet/**"
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup variables
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA=$short_sha" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.CI_REGISTRY }}
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./warmbet/
          file: ./warmbet/Dockerfile
          push: true
          tags: ${{ vars.CI_REGISTRY }}/warmbet:${{ env.SHORT_SHA }}
